---
#Install java 8 dependency for marathon in debian
- name: Add java repository to ub14
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "14"

- name: Create man dir to patch ubuntu 14
  file: path=/usr/share/man/man1 state=directory recurse=yes

- name: Ensure Java is installed
  apt: name=openjdk-8-jre-headless state=present update_cache=yes

- name: Select java version 8 (Problems with java 9)
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

- name: Add key for Mesosphere repository for Debian systems
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xE56151BF state=present

- name: Determine Linux distribution distributor
  shell: lsb_release -is | tr '[:upper:]' '[:lower:]'
  register: release_distributor

- name: Determine Linux distribution codename
  command: lsb_release -cs
  register: release_codename

- name: Add Mesosphere repository to sources list
  copy:
    content: "deb http://repos.mesosphere.io/{{release_distributor.stdout}} {{release_codename.stdout}} main"
    dest: /etc/apt/sources.list.d/mesosphere.list
    mode: 0644

- name: Install marathon package in Debian systems
  apt: pkg=marathon state=present update_cache=yes
