- name: Include "{{ansible_os_family}}" marathon recipe
  include: "{{ansible_os_family}}.yml"

- name: Create marathon conf folder
  file: 
    path: /opt/marathon/conf
    state: directory
    mode: 0755

- name: Set Mesos-Marathon credentials
  copy:
    content: "{{secret}}"
    dest: /opt/marathon/conf/marathon-secret
    mode: 0644

- name: Set Marathon configuration
  blockinfile:
    path: /etc/default/marathon
    insertafter: EOF
    block: |
      MARATHON_MASTER="zk://{{marathon_mesos_master}}:2181/mesos"
      MARATHON_ZK="zk://{{marathon_mesos_master}}:2181/marathon"
      MARATHON_MESOS_ROLE="{{marathon_mesos_role}}"
      MARATHON_HTTP_CREDENTIALS="{{marathon_username}}:{{marathon_password}}"
      MARATHON_MESOS_AUTHENTICATION=""
      MARATHON_MESOS_AUTHENTICATION_PRINCIPAL="{{principal}}"
      MARATHON_MESOS_AUTHENTICATION_SECRET_FILE=/opt/marathon/conf/marathon-secret
      MARATHON_MESOS_USER="{{marathon_mesos_user}}"

- name: start marathon
  service: name=marathon state=started enabled=yes

- block:
  - set_fact: ports=""
  - set_fact: ports="{{ ports|list + [ item ] }}"
    with_sequence: start=10000 end={{ marathon_lb_last_port }}
  - set_fact: ports="{{ ports + ['9090'] }}"

  - name: Launch marathon-lb container
    docker_container:
      restart: yes
      name: marathon-lb
      image: "mesosphere/marathon-lb"
      command: "sse --group external -m http://{{ marathon_mesos_master }}:8080 --auth-credentials {{ marathon_username }}:{{ marathon_password }}"
      state: started
      ports: "{{ports}}"
      env:
         PORTS: '9090'
      network_mode: "host"
  when: marathon_lb