- name: create etc directory
  file: state=directory path=/etc/marathon

- name: Set Mesos-Marathon credentials
  copy:
    content: "{{mesos_secret}}"
    dest: /etc/marathon/marathon-secret
    mode: 0644

- name: run marathon container
  docker_container:
    name: marathon
    image: "{{ marathon_image }}"
    state: started
    detach: true
    restart_policy: always
    network_mode: host
    volumes:
    - "/etc/marathon/marathon-secret:/etc/marathon/marathon-secret"
    env:
      MARATHON_MASTER="zk://{{marathon_mesos_master}}:2181/mesos"
      MARATHON_ZK="zk://{{marathon_mesos_master}}:2181/marathon"
      MARATHON_MESOS_ROLE="{{marathon_mesos_role}}"
      MARATHON_HTTP_CREDENTIALS="{{marathon_username}}:{{marathon_password}}"
      MARATHON_MESOS_AUTHENTICATION=""
      MARATHON_MESOS_AUTHENTICATION_PRINCIPAL="{{mesos_principal}}"
      MARATHON_MESOS_AUTHENTICATION_SECRET_FILE=/etc/marathon/marathon-secret
      MARATHON_MESOS_USER="{{marathon_mesos_user}}"

- block:
  - name: Launch marathon-lb container
    docker_container:
      restart: yes
      name: marathon-lb
      image: "mesosphere/marathon-lb"
      command: "sse --group external -m http://{{ marathon_mesos_master }}:8080 --auth-credentials {{ marathon_username }}:{{ marathon_password }}"
      state: started
      env:
         PORTS: '9090'
      network_mode: "host"
  when: marathon_lb