- name: Include "{{ansible_os_family}}" marathon recipe
  include: "{{ansible_os_family}}.yml"

- name: Set Marathon configuration
  blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    block: |
      MARATHON_MASTER="zk://{{ansible_default_ipv4.address}}:2181/mesos"
      MARATHON_ZK="zk://{{ansible_default_ipv4.address}}:2181/marathon"
      MARATHON_MESOS_ROLE="{{marathon_mesos_role}}"
      MARATHON_HTTP_CREDENTIALS="{{marathon_username}}:{{marathon_password}}"
      MARATHON_MESOS_AUTHENTICATION=""
      MARATHON_MESOS_AUTHENTICATION_PRINCIPAL="{{principal}}"
      MARATHON_MESOS_AUTHENTICATION_SECRET_FILE="{{secret}}"

- name: start marathon
  service: name=marathon state=started enabled=yes
