    #Install java 8 dependency for marathon in debian
    - name: Add webupd8 ppa repository
      apt_repository: repo='ppa:webupd8team/java'
      when: ansible_os_family == "Debian"

    - name: apt update
      apt: update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Auto accept oracle jdk license
      shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
      when: ansible_os_family == "Debian"
 
    - name: Install java8
      shell: apt-get install -y oracle-java8-installer ca-certificates
      when: ansible_os_family == "Debian"

    - name: Install oracle-java8-set-default package
      apt: pkg=oracle-java8-set-default state=present update_cache=yes
      when: ansible_os_family == "Debian"

    #Install java 8 dependency for marathon in redhat
    - name: Download Oracle Java 8
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-linux-x64.rpm
        dest: /tmp/jdk-8u66-linux-x64.rpm
        headers: 'Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
      when: ansible_os_family == "RedHat"

    - name: Install oracle java 8 (jdk-8u66)
      yum: pkg=/tmp/jdk-8u66-linux-x64.rpm state=present
      when: ansible_os_family == "RedHat"

    - name: Install marathon repo
      yum: pkg=http://repos.mesosphere.com/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm state=present
      when: ansible_os_family == "RedHat"

    - name: Add keyserver
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E56151BF
      when: ansible_os_family == "Debian"

    - name: Create lst file ubuntu 14
      copy: content="deb http://repos.mesosphere.com/ubuntu trusty main" dest=/etc/apt/sources.list.d/mesosphere.list
      when: ansible_os_family == "Debian" and ansible_distribution_major_version == "14"

    - name: Create lst file ubuntu 16
      copy: content="deb http://repos.mesosphere.com/ubuntu xenial main" dest=/etc/apt/sources.list.d/mesosphere.list
      when: ansible_os_family == "Debian" and ansible_distribution_major_version == "16"

    - name: Install marathon package in Debian systems
      apt: pkg=marathon state=present update_cache=yes
      when: ansible_os_family == "Debian"
 
    - name: Install marathon package in RedHat systems
      yum: name=marathon state=present update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: start marathon
      service: name=marathon state=started enabled=yes
